### obtener todos los characters
GET http://localhost:3000/api/persona

### obtener un character -- busqueda por id
GET http://localhost:3000/api/persona/56756

### crear un nuevo character
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "name": "Raul",
    "lastname": "warrior",
    "dni": 56756
}

### modificar un character (PUT - modificacion completa e idempotente)
PUT http://localhost:3000/api/persona/43644808
Content-Type: application/json
    
{
    "name": "Martina",
    "lastname": "Vivarco",
    "dni": 3423523456346
}

### modificar un character (PATCH - modificacion parcial de un recurso)
PATCH http://localhost:3000/api/persona/56756
Content-Type: application/json

{
    "name": "CamilaXD"
}

### eliminar un character
DELETE http://localhost:3000/api/persona/3423523456346
