### obtener todas las personas
GET http://localhost:3000/api/persona

### obtener una persona -- busqueda por id
GET http://localhost:3000/api/persona/56756

### crear una nueva persona
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "name": "Raul",
    "lastname": "warrior",
    "dni": 56756
}

### modificar una persona (PUT - modificacion completa e idempotente)
PUT http://localhost:3000/api/persona/43644808
Content-Type: application/json
    
{
    "name": "Martina",
    "lastname": "Vivarco",
    "dni": 3423523456346
}

### modificar una persona (PATCH - modificacion parcial de un recurso)
PATCH http://localhost:3000/api/persona/56756
Content-Type: application/json

{
    "name": "CamilaXD"
}

### eliminar una persona
DELETE http://localhost:3000/api/persona/3423523456346
